--- 
title: "EDAV Final Project (Group 9)"
author: "Cong Chen, Taichen Zhou, Yichen Huang"
date: "`r Sys.Date()`"
output: pdf_document
site: bookdown::bookdown_site
---

# Introduction
For the final project, our team will focus on discovering the relationship between the disease Tuberculosis (TB) spread worldwide and the TB vaccine - Bacille Calmette-Guerin (BCG). The TB dataset collected from WHO covers numerous information, including but not limited to the budget, new cases, treatment success rate, etc., from 1980 - 2021.  The BCG dataset is collected from UNICEF, including the vaccination rate for each country from 1980 - 2021.

TB is caused by a bacterium called Mycobacterium tuberculosis. The bacteria usually attract the lungs, but TB bacteria can affect any part of the body, such as the kidney, spine, and brain. Not everyone infected with TB bacteria becomes sick. As a result, two TB-related conditions exist latent TB infection (LTBI) and TB disease. If not treated properly, TB disease can be fatal. (TB Basic Facts) [https://www.cdc.gov/tb/topic/basics/default.htm]  TB bacteria spread through the air from one person to another. When a person with TB disease of the lungs or throat coughs, speaks or sings, TB bacteria can get into the air. People nearby may breathe in these bacteria and become infected. (TB Spread) [https://www.cdc.gov/tb/topic/basics/howtbspreads.htm] 

TB vaccine - BCG is a vaccine for tuberculosis (TB) disease. This vaccine is not widely used in the United States. However, it is often given to infants and small children in other countries where TB is common. BCG does not always protect people from getting TB. (BCG Basic Facts) [https://www.cdc.gov/tb/topic/basics/vaccines.htm]
