---
output:
  pdf_document: default
  html_document: default
---
# Proposal
## Research topic
* Recent reports have shown that Tuberculosis deaths and disease increased during the COVID-19 pandemic. This news inspires us to research the historical trend of the number of patients with TB, and vice versa our research can verify the authenticity of the news.
(https://www.who.int/news/item/27-10-2022-tuberculosis-deaths-and-disease-increase-during-the-covid-19-pandemic)
 
* By using visualization methods, we can investigate the type of people who have a higher risk of catching TB when comparing the number of patients with TB of different genders, ages, and so on. As TB as the leading cause of death among people with HIV,  it might be interesting to study how HIV infection rate influences the TB infection situation in different country and among years. We will also explore the relationship between TB and BCG, such as the relationship between the number of patients with TB and the percentage of people vaccinated with the BCG vaccine. Also, we want to compare the data between different regions, and so on. In this way, we can know the difference in the degree of TB prevention in different regions. 
 
## Data availability
### Tuberculosis(TB) notification and outcome dataset
   * The source of the dataset is the global tuberculosis report published by World Health Organization(WHO). The dataset provided by countries to WHO and estimates of TB burden generated by WHO for the Global Tuberculosis Report.[Global Tuberculosis Report] (https://www.who.int/teams/global-tuberculosis-programme/data)
   * The column explanation(dictionary) is also contained in the link above. The data dictionary file will cover variable names with corresponding definitions. For the categorical variables, the dictionary will also provide the encoding method and meaning of the code.
   * Countries provide the data to WHO and we are not sure how exactly those countries collected the data. We conjecture that the data are collected from every hospital by national public health agencies like the Centers for Disease Control and Prevention in the United States. Because the dataset contains the TB data from 1980 to 2021, the collection method may also vary.
   * The TB dataset is in CSV(comma-separated value). We can apply read.csv() in R to import the CSV file to the R data frame.
   * The TB dataset contains the annual data for the period of 41 years, so we assume that the frequency of updates is once per year. The TB dataset is composed of 198 features of TB data from 217 countries from 1980 to 2021, although there are huge amounts of missing data which will be handled in future analysis. 
   * The TB dataset contains 595 variables including the budget, community engagement, contacts preventive treatment, estimates, outcomes, etc.
   * According to the topics we are interested in, we cannot analyze all variables. There are several potentially related features can be drawn from the dataset. 
     * c_newinc (Total of new and relapse cases and cases with unknown previous TB treatment history)
     * age_group (in years)
     * e_inc_tbhiv_num (Estimated incidence of TB cases who are HIV-Positive)
     * Etc.
 
### Vaccination dataset
   * The source is from the United Nations International Children’s Emergency Fund(UNICEF) which is an agency of the United Nations responsible for providing humanitarian and developmental aid to children worldwide. The UNICEF data will cover the situation of children and women worldwide. [Immunization Data] (https://data.unicef.org/resources/dataset/immunization/)
   * According to the UNICEF data and analytics introduction, UNICEF’s Data Team is responsible for the collection, validation, analysis, use, and communication of the most statistically sound. The team upholds the quality, integrity, and organization of these data. [UNICEF Data] (https://data.unicef.org/about-us/) 
   * The collected data is in Microsoft Excel Spreadsheet format(.xlsx). The data set is updated annually for 168 countries worldwide from 1980 - 2021.
   * Same as the CSV file, the .xlsx file can be imported to R and converted to the data frame by the readxl package.
   * The structure of the dataset is clear; the spreadsheet covers the BCG vaccination rate for 168 countries in the world in past 41 years. The dataset is not perfect, there exists some missing data for some countries in the period of time. It may cause some problems for our future analysis.
   * The number of countries recorded in the spreadsheet from UNICEF is less than the number of countries covered in the WHO dataset. Therefore, during the analysis of the TB and BCG vaccines, some countries will be ignored.
 
### More datasets may be introduced to help our analysis in the future. 


